### ISSUE TITLE
Create User Stories in Backlog.MD File

### ISSUE THREAD

**Issue by selimensar** [zaraana/Hyf-Website#9]
Everyone will add at least 2 user stories:
- [/[backlog.md](https://github.com/zaraana/Hyf-Website/blob/main/Planning/Backlog.md)]()
  - [x] Furkan
  - [x] Emely
  - [x] Zehra
  - [x] Zara
  - [x] Joexy
  - [x] Selim

**Comment by zaraana** [comment]
Great job @selimensar ;)  thank you!
